# Generated by Django 4.2.13 on 2024-06-17 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='deleted_users',
            field=models.ManyToManyField(blank=True, related_name='deleted_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
