# Generated by Django 4.2.13 on 2024-06-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chats_deleted_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
