# Generated by Django 4.2.13 on 2024-06-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_messages_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
