# Generated by Django 4.2.13 on 2024-06-24 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_messages_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_name', models.CharField(default='AI', max_length=100)),
                ('messages', models.ManyToManyField(related_name='AI', to='api.messages')),
                ('user_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
