# Generated by Django 4.2.13 on 2024-06-24 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ai',
            name='messages',
        ),
        migrations.AddField(
            model_name='messages',
            name='ai',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.ai'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
