# Generated by Django 4.2.13 on 2024-06-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_ai_messages_messages_ai_alter_messages_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai',
            name='ai_name',
            field=models.CharField(default='Personal AI', max_length=100),
        ),
    ]
