# Generated by Django 4.2.13 on 2024-06-24 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_ai_ai_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='ai',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.ai'),
        ),
    ]
